### ISSUE TITLE
Publish TCPStream on Hex.pm

### ISSUE THREAD

**Issue by Havvy** [hamiltop/structurez#1]
Is there a chance you can take TCPStream, and publish it on Hex.pm. 

If you don't want to, can I have express permission to post it on Hex.pm. Yes, it's MIT and I could do so without asking, but that would be regarded as rude.

**Comment by hamiltop** [comment]
No problem. Give me a day or so to get around to it.

**Comment by hamiltop** [comment]
Done. Let me know if you have any issues.

**Comment by Havvy** [comment]
Will do, will pull into my project tomorrow.
